name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Log in to Docker Hub
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    # 3. Build Docker image
    - name: Build Docker image
      run: |
        IMAGE_NAME=siri019/dotnetapp:latest
        docker build -t $IMAGE_NAME ./WebApp
        docker push $IMAGE_NAME

    # 4. Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 5. Update kubeconfig
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name my-app --region us-east-1

    # 6. Deploy with Helm
    - name: Deploy to EKS
      run: |
        helm upgrade --install my-app ./helm-chart \
          --set image.repository=yourusername/webapp \
          --set image.tag=latest
